"""Fits HeadPredictor's weights to recorded head motion.

Two linear predictors are fitted: a very smooth one for a (nearly) still head (typing, talking,
reading) and a sharp one for movement; the app blends them by head speed. Each maps 39 features of
recent motion (gyro history + accelerometer, see HeadPredictor.swift) to the head rotation over a
horizon, fitted to minimise prediction error plus MU × its frame-to-frame change.

1. Record head motion: the app's tracking calibration (~/Library/Logs/XRealDesk/calibration-*/imu.csv)
   and/or `post com.xrealdesk.recordIMU 60` (imu-*.csv).
2. Export what the app's predictor sees, into one folder (CALDIR):
     xrcheck dumpcal testdata/air2pro-calibration.json <imu.csv> $CALDIR/cal-<name>.csv
   Files named cal-calib*.csv count WEIGHT_CALIB times (the wearer's own guided session).
3. CALDIR=... python3 scripts/fit-head-predictor.py Sources/XRCore/HeadPredictorWeights.swift
"""
import numpy as np, sys, os, glob

S = os.environ.get("CALDIR", ".") + "/"
files = sorted(os.path.basename(f) for f in glob.glob(S + "cal-*.csv"))
GB = [0, 2, 4, 8, 16, 32, 64, 128]; AB = [0, 2, 4, 8, 16, 32, 64]; SLOW = 300
HS = [10, 20, 30, 40, 50, 60, 70, 80]
MU_STILL, MU_MOVING = 30.0, 5.0          # jitter penalty: smooth when still, sharp when moving
BLEND_START, BLEND_FULL = 5.0, 20.0     # head speed (°/s) over which the moving predictor takes over (typing stays smooth)
WEIGHT_CALIB = int(os.environ.get("WEIGHT_CALIB", "2"))
LAM = 1e-5


def qmul(a, b):
    x1, y1, z1, w1 = a.T; x2, y2, z2, w2 = b.T
    return np.stack([w1*x2+x1*w2+y1*z2-z1*y2, w1*y2-x1*z2+y1*w2+z1*x2, w1*z2+x1*y2-y1*x2+z1*w2, w1*w2-x1*x2-y1*y2-z1*z2], 1)


def qlog(q):
    q = q * np.sign(q[:, 3:4] + 1e-12); v = q[:, :3]; n = np.linalg.norm(v, axis=1, keepdims=True)
    return v / np.maximum(n, 1e-12) * 2 * np.arctan2(n, q[:, 3:4])


def load(f):
    d = np.loadtxt(S + f, delimiter=",", skiprows=1); w = d[:, 1:4]; a = d[:, 4:7]; q = d[:, 7:11]
    cw = np.vstack([np.zeros((1, 3)), np.cumsum(w, 0)]); ca = np.vstack([np.zeros((1, 3)), np.cumsum(a, 0)])
    n = len(w); idx = np.arange(SLOW + 5, n - max(HS) - 1); e = idx + 1
    X = [(cw[e-lo] - cw[e-hi]) / (hi - lo) for lo, hi in zip(GB[:-1], GB[1:])]
    slow = (ca[e] - ca[e-SLOW]) / SLOW
    X += [(ca[e-lo] - ca[e-hi]) / (hi - lo) - slow for lo, hi in zip(AB[:-1], AB[1:])]
    X = np.concatenate(X, 1)
    Y = {h: qlog(qmul(q[idx] * np.array([-1, -1, -1, 1]), q[idx+h])) for h in HS}
    return X, Y


D = {f: load(f) for f in files}


def fit(h, mu):
    parts = []
    for f in files:
        X, Y = D[f]
        parts += [(X, Y[h])] * (WEIGHT_CALIB if f.startswith("cal-calib") else 1)
    A = np.concatenate([p[0] for p in parts]); B = np.concatenate([p[1] for p in parts])
    dA = np.concatenate([p[0][8:] - p[0][:-8] for p in parts]); dB = np.concatenate([p[1][8:] - p[1][:-8] for p in parts])
    s = A.std(0) + 1e-12; nf = A.shape[1]
    W = np.linalg.solve((A/s).T @ (A/s) + mu * (dA/s).T @ (dA/s) + LAM * len(A) * np.eye(nf), (A/s).T @ B + mu * (dA/s).T @ dB)
    return W / s[:, None]


def swift(name, sets):
    out = [f"    static let {name}: [[SIMD3<Float>]] = ["]
    for W in sets:
        out.append("        [" + ", ".join(f"SIMD3({r[0]:.6g}, {r[1]:.6g}, {r[2]:.6g})" for r in W) + "],")
    out.append("    ]")
    return out


if __name__ == "__main__" and "--net" not in sys.argv:
    print("fitting on:", ", ".join(files))
    still = [fit(h, MU_STILL) for h in HS]
    moving = [fit(h, MU_MOVING) for h in HS]
    out = ["// Generated by scripts/fit-head-predictor.py from recorded head motion (" + ", ".join(f[4:-4] for f in files) + ").",
           "// Two predictors blended by head speed: smooth when still, sharp when moving. Do not edit.", "",
           "extension HeadPredictor {",
           f"    static let horizonsMs: [Float] = {HS}",
           f"    static let blendDegreesPerSecond: (start: Float, full: Float) = ({BLEND_START}, {BLEND_FULL})"]
    out += swift("weightsStill", still) + swift("weightsMoving", moving) + ["}", ""]
    open(sys.argv[1], "w").write("\n".join(out))
    print("wrote", sys.argv[1])


def fit_net(hidden=(64, 64), every=3, seed=0):
    """Small neural net (sklearn MLP, tanh) mapping the 39 features to the rotation (degrees) at
    every horizon in HS. Used by the app while the head moves (see HeadPredictor.Model.hybrid)."""
    from sklearn.neural_network import MLPRegressor
    from sklearn.preprocessing import StandardScaler
    Xs, Ys = [], []
    for f in files:
        X, Y = D[f]
        reps = WEIGHT_CALIB if f.startswith("cal-calib") else 1
        T = np.degrees(np.concatenate([Y[h] for h in HS], 1))    # (n, 3 * len(HS))
        for _ in range(reps):
            Xs.append(X[::every]); Ys.append(T[::every])
    X = np.concatenate(Xs); T = np.concatenate(Ys)
    sc = StandardScaler().fit(X)
    m = MLPRegressor(hidden_layer_sizes=hidden, activation="tanh", alpha=1e-3, early_stopping=True,
                     max_iter=300, random_state=seed, learning_rate_init=1e-3)
    m.fit(sc.transform(X), T)
    return sc, m


def swift_net(sc, m):
    fl = lambda a: ", ".join(f"{v:.7g}" for v in np.asarray(a, dtype=np.float64).ravel())
    W1, W2, W3 = m.coefs_; b1, b2, b3 = m.intercepts_
    out = ["// Generated by scripts/fit-head-predictor.py --net: a small neural net (39 → " +
           " → ".join(str(w.shape[1]) for w in m.coefs_) + ", tanh) predicting the head rotation (degrees) at every",
           "// horizon in HeadPredictor.horizonsMs from the same 39 features. Weights row-major [in][out]. Do not edit.", "",
           "extension HeadPredictor {",
           f"    static let netSizes: [Int] = [{W1.shape[0]}, {W1.shape[1]}, {W2.shape[1]}, {W3.shape[1]}]",
           f"    static let netMean: [Float] = [{fl(sc.mean_)}]",
           f"    static let netScale: [Float] = [{fl(sc.scale_)}]",
           f"    static let netW1: [Float] = [{fl(W1)}]", f"    static let netB1: [Float] = [{fl(b1)}]",
           f"    static let netW2: [Float] = [{fl(W2)}]", f"    static let netB2: [Float] = [{fl(b2)}]",
           f"    static let netW3: [Float] = [{fl(W3)}]", f"    static let netB3: [Float] = [{fl(b3)}]",
           "}", ""]
    return "\n".join(out)


if __name__ == "__main__" and "--net" in sys.argv:
    sc, m = fit_net()
    path = sys.argv[sys.argv.index("--net") + 1]
    open(path, "w").write(swift_net(sc, m))
    print("wrote", path, "(net, validation R²", f"{m.best_validation_score_:.4f})")
