"""Fits HeadPredictor's weights to recorded head motion.

1. Record:  post com.xrealdesk.recordIMU 60   (→ ~/Library/Logs/XRealDesk/imu-*.csv; typing, talking, turning)
2. Export what the app's predictor sees:
     xrcheck dumpcal testdata/air2pro-calibration.json imu-X.csv $CALDIR/cal-X.csv
3. CALDIR=... python3 scripts/fit-head-predictor.py 1e-5 Sources/XRCore/HeadPredictorWeights.swift 5
   (args: ridge, output file, jitter penalty). Prints leave-one-out error vs constant speed.
"""
import numpy as np, sys, os, glob
S=os.environ.get("CALDIR",".")+"/"
files=sorted(os.path.basename(f) for f in glob.glob(S+"cal-*.csv"))
GB=[0,2,4,8,16,32,64,128]; AB=[0,2,4,8,16,32,64]; SLOW=300
HS=[10,20,30,40,50,60,70,80]
def qmul(a,b):
    x1,y1,z1,w1=a.T; x2,y2,z2,w2=b.T
    return np.stack([w1*x2+x1*w2+y1*z2-z1*y2, w1*y2-x1*z2+y1*w2+z1*x2, w1*z2+x1*y2-y1*x2+z1*w2, w1*w2-x1*x2-y1*y2-z1*z2],1)
def qlog(q):
    q=q*np.sign(q[:,3:4]+1e-12); v=q[:,:3]; n=np.linalg.norm(v,axis=1,keepdims=True)
    ang=2*np.arctan2(n,q[:,3:4]); return v/np.maximum(n,1e-12)*ang
def load(f):
    d=np.loadtxt(S+f,delimiter=",",skiprows=1); w=d[:,1:4]; a=d[:,4:7]; q=d[:,7:11]
    cw=np.vstack([np.zeros((1,3)),np.cumsum(w,0)]); ca=np.vstack([np.zeros((1,3)),np.cumsum(a,0)])
    n=len(w); idx=np.arange(SLOW+5,n-max(HS)-1)
    e=idx+1   # prefix end (exclusive) = includes sample idx
    X=[(cw[e-lo]-cw[e-hi])/(hi-lo) for lo,hi in zip(GB[:-1],GB[1:])]
    slow=(ca[e]-ca[e-SLOW])/SLOW
    X+=[(ca[e-lo]-ca[e-hi])/(hi-lo)-slow for lo,hi in zip(AB[:-1],AB[1:])]
    X=np.concatenate(X,1)
    qi=q[idx]; qinv=qi*np.array([-1,-1,-1,1])
    Y={h:qlog(qmul(qinv,q[idx+h])) for h in HS}
    speed=np.degrees(np.linalg.norm(X[:,0:3],axis=1))
    return X,Y,speed
D={f:load(f) for f in files}
nf=D[files[0]][0].shape[1]
MU=float(sys.argv[3]) if len(sys.argv)>3 else 0.0
def fit(train,h,lam):
    A=np.concatenate([D[f][0] for f in train]); B=np.concatenate([D[f][1][h] for f in train])
    dA=np.concatenate([D[f][0][8:]-D[f][0][:-8] for f in train]); dB=np.concatenate([D[f][1][h][8:]-D[f][1][h][:-8] for f in train])
    s=A.std(0)+1e-12; As=A/s; dAs=dA/s
    W=np.linalg.solve(As.T@As+MU*dAs.T@dAs+lam*len(A)*np.eye(nf),As.T@B+MU*dAs.T@dB)
    return W/s[:,None]   # (nf,3) in raw units
lam=float(sys.argv[1]) if len(sys.argv)>1 else 1e-5
for h in (40,):
    for test in files:
        W=fit([f for f in files if f!=test],h,lam)
        X,Y,sp=D[test]; P=X@W
        cv=(X[:,0:3]*2+X[:,3:6]*2+X[:,6:9]*4)/8*h*0.001
        for name,m in (("working",sp<10),("turning",sp>=10)):
            if m.sum()<100: continue
            e=lambda P_: np.degrees(np.sqrt((np.linalg.norm(Y[h][m]-P_[m],axis=1)**2).mean()))
            E=Y[h]-P; Ec=Y[h]-cv; mm=m[8:]&m[:-8]
            j=lambda E_: np.degrees(np.sqrt((np.linalg.norm((E_[8:]-E_[:-8])[mm],axis=1)**2).mean()))
            print(f"h={h} MU={MU} {test[4:18]:14} {name:8} const-vel {e(cv):.4f}° jit {j(Ec):.4f}°   learned {e(P):.4f}° jit {j(E):.4f}°")
if len(sys.argv)>2:
    out=["// Generated by scratch train.py from recorded head motion (typing, turning, talking). Do not edit.",
         "// Per horizon (ms): weights mapping the 39 features (HeadPredictor.features) to the head-frame",
         "// rotation vector (rad) over that horizon.","",
         "extension HeadPredictor {",
         f"    static let horizonsMs: [Float] = {HS}",
         "    static let weights: [[SIMD3<Float>]] = ["]
    for h in HS:
        W=fit(files,h,lam)
        out.append("        ["+", ".join(f"SIMD3({r[0]:.6g}, {r[1]:.6g}, {r[2]:.6g})" for r in W)+"],")
    out+=["    ]","}",""]
    open(sys.argv[2],"w").write("\n".join(out)); print("wrote",sys.argv[2])
